### PR TITLE
Add a UI to apply a "compact" mode, to exercise re-layout of the sticky.html demo.

### PR DESCRIPTION
**Pull request by chrishtr**

### CODE REVIEW

**Comment by chrishtr** [comment]
I don't have authority to merge this PR. Either you should do it or give me permissions.

**Comment by fergald** [comment]
Tested it locally, merge is good.

**Comment by fergald** [comment]
> I don't have authority to merge this PR. Either you should do it or give me permissions.

I did it but I think it's fine for you to have access, @domenic  ?

**Comment by domenic** [comment]
Added!

**Pull request merged**
